# Generated by Django 5.2.1 on 2025-05-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_sistemaproducao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicoviveiro',
            name='sistemas_de_producao',
        ),
        migrations.AddField(
            model_name='historicoviveiro',
            name='sistemasDeProducao',
            field=models.ManyToManyField(to='catalog.sistemaproducao'),
        ),
        migrations.AlterField(
            model_name='historicoviveiro',
            name='numPlantas',
            field=models.IntegerField(blank=True, help_text='Numero de plantas do viveiro', null=True, verbose_name='Numero de plantas do viveiro'),
        ),
    ]
