# Generated by Django 5.2.1 on 2025-06-28 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_historicoviveiro_sistemas_de_producao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoviveiro',
            name='viveiro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.viveiro'),
        ),
    ]
