# Generated by Django 5.2.1 on 2025-06-28 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_historicoviveiro_viveiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoviveiro',
            name='viveiro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.viveiro'),
            preserve_default=False,
        ),
    ]
