# Generated by Django 5.2.1 on 2025-06-28 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_historicoviveiro_viveiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicopropriedade',
            name='propriedade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.propriedade'),
            preserve_default=False,
        ),
    ]
