# Generated by Django 5.2.1 on 2025-06-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_historicopropriedade_propriedade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicopropriedade',
            name='sistemasDeProducao',
            field=models.ManyToManyField(to='catalog.sistemaproducao', verbose_name='Sistema de Produção'),
        ),
        migrations.AlterField(
            model_name='historicoviveiro',
            name='sistemasDeProducao',
            field=models.ManyToManyField(to='catalog.sistemaproducao', verbose_name='Sistema de Produção'),
        ),
    ]
